### ISSUE TITLE
Dryer's dataset 2018 (coded already by @Macyl)

### ISSUE THREAD

**Issue by LinguList** [cldf-datasets/cldf-datasets#12]
Dryer, M.S. (2018). On the order of demonstrative, numeral, adjective, and noun. Language 94(4), 798-833. doi:10.1353/lan.2018.0054.

**Comment by SimonGreenhill** [comment]
This is the same as https://github.com/cldf-datasets/cldf-datasets/issues/7, right?

**Comment by xrotwang** [comment]
See https://github.com/cldf-datasets/dryerorder
