### ISSUE TITLE
syllable structure and phoneme inventories by Easterday 2019 

### ISSUE THREAD

**Issue by LinguList** [cldf-datasets/cldf-datasets#13]
The data can be extracted from the github source: https://github.com/langsci/249/blob/master/chapters/appendixB.tex

This book has appeared in langscipress:

http://langsci-press.org/catalog/book/249

And data is CC-BY licensed, see https://doi.org/10.5281/zenodo.3268721

**Comment by xrotwang** [comment]
Started: https://github.com/cldf-datasets/easterdaysyllablestructure
