### ISSUE TITLE
Inventories for Greenhill et al "Journal of the IPA"

### ISSUE THREAD

**Issue by tresoldi** [cldf-datasets/cldf-datasets#28]
As available at https://github.com/SimonGreenhill/jipa

**Comment by tresoldi** [comment]
Can somebody with permission please set the "new dataset" label and assign it to me?

**Comment by SimonGreenhill** [comment]
Baird et al :)

**Comment by tresoldi** [comment]
Initial version (prepared for the inventory study, more work is necessary) at https://github.com/cldf-datasets/jipa
