### ISSUE TITLE
Ruhlen database (Global Linguistic Database)

### ISSUE THREAD

**Issue by cormacanderson** [cldf-datasets/cldf-datasets#37]
PDF here https://starling.rinet.ru/typology.pdf

Online here https://starling.rinet.ru/cgi-bin/response.cgi?root=config&morpho=0&basename=\data\typol\typology&first=1

Assign: @LinguList and me
Lable: new dataset

**Comment by LinguList** [comment]
We have added this to a new currently private repository now, where we 
can follow up on issues (same for upsid, you should receive an 
invitation soon or have already received it).
