### ISSUE TITLE
Dryer (2018), On the Order of Demonstrative, Numeral, Adjective and Noun

### ISSUE THREAD

**Issue by chrzyki** [cldf-datasets/cldf-datasets#7]
Article: 

* [DryerDemNumAdjN.pdf](https://github.com/cldf-datasets/cldf-datasets/files/2827537/DryerDemNumAdjN.pdf)

Supplement with tables and relevant information:

* [DryerDemNumAdjN_Supplement.pdf](https://github.com/cldf-datasets/cldf-datasets/files/2827540/DryerDemNumAdjN_Supplement.pdf)
* Text version: [Dryer_DNAnTable.txt](https://github.com/cldf-datasets/cldf-datasets/files/2827542/Dryer_DNAnTable.txt)

**Comment by SimonGreenhill** [comment]
closed in favor of #12

**Comment by xrotwang** [comment]
started at https://github.com/cldf-datasets/dryerorder
